services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    container_name: backend-dev
    env_file:
      - .env
    volumes:
      - ./database:/src/database
      - ./backend/app:/src/app
      - ./backend/tests:/src/tests
    ports:
      - 8000:8000
    networks:
      dev:
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - 8080:80
    networks:
      dev:

networks:
  dev:
    driver: bridge
  