services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      main:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - /workspaces/Bean-and-Brew/database:/src/database
    env_file:
      - .env
    environment:
      - JWT_KEY=$JWT_KEY
      - JWT_ALGORITHM=$JWT_ALGORITHM
      - JWT_EXPIRY_MINUTES=$JWT_EXPIRY_MINUTES
      - DB_URL=$DB_URL
      - ORIGINS=$ORIGINS
    networks: 
      main:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      main:
  
networks:
  main:
    driver: bridge
