services:
  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - backend/.env
    ports:
      - "5000:8000"
    volumes:
      - /workspaces/Bean-and-Brew/database:/src/database
    networks: 
      main:
    
  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      VITE_API_URL: http://localhost:5000/
    ports:
      - "8080:80"
    networks: 
      main:

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks: 
      main:

networks:
  main:
    driver: bridge
