FROM python:3.10

WORKDIR /src/
COPY ./requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

ENV PYTHONPATH=/src

COPY ./app /src/app
COPY ./tests /src/tests
COPY ./run_tests.py /src/

RUN touch test.db

EXPOSE 8000
CMD uvicorn app.main:app --host 0.0.0.0 --reload